# Generated by Django 4.1.7 on 2023-03-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='cat_image/')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=255)),
                ('opt_2', models.CharField(max_length=255)),
                ('opt_3', models.CharField(max_length=255)),
                ('opt_4', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('time_limit', models.IntegerField()),
                ('right_opt', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizcategory')),
            ],
        ),
    ]
